### ISSUE TITLE
new updated version 2 fails on looking for file 'false'

### ISSUE THREAD

**Issue by sagiegurari** [jsdoc2md/grunt-jsdoc-to-markdown#10]
I didn't change my grunt build which is like this:

````js
jsdoc2md: {
   api: {
    options: {
      index: true,
      private: false
    },
    src: 'angular-web-notification.js',
    dest: 'docs/api.md'
  }
}
````

added console.log(options) in line 16 of jsdoc2md.js to see the options which are:

````js
{ index: true,
  private: false,
  files: [ 'angular-web-notification.js' ] }
````

and the error I get is:

````sh
Running "jsdoc2md:api" (jsdoc2md) task
>> writing docs/api.md
Fatal error: ERROR: Unable to find the source file or directory <path>\angular-web-notification\false
````

For some reason it is not looking for the files, but using 'false' instead.

**Comment by 75lb** [comment]
Hi, i just tested grunt-jsdoc-to-markdown again - everything seems to work fine.

I'm 99% this is an issue with your setup. Still, please send me steps to reproduce the issue so i can check for myself. 

By the way, `index` is not a valid option. Please see [here](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoc2mdrenderoptions--promise) for the correct options.

**Comment by sagiegurari** [comment]
I'll remove the options completely and check it just in case.
i did a fresh npm install to update all modules, so i'm not even sure which module throws that error exactly since you have many sub modules

**Comment by 75lb** [comment]
if you tell me which code/branch to check out, and what commands to run i will check it myself.. I can't diagnose the issue without reproduction steps.. cheers.

**Comment by sagiegurari** [comment]
ok, so the issue is that if i have the option: **private: false** the error happens.
i do remember there was such an option to control if to generate jsdoc for public and private or just public apis.

**Comment by sagiegurari** [comment]
anyway, i removed the option and now all is good. so i'm closing this case.
but you should check it out maybe to see why it causes the task to fail because I do remember such an option in the past.

**Comment by sagiegurari** [comment]
by the way, thanks for the help 👍 
the grunt task is really really helpful for all my projects.

**Comment by 75lb** [comment]
i already did check it out - grunt-jsdoc-to-markdown works fine with the `private` option (i'm testing it locally now).. that's why i'm asking for reproduction steps - because i have not found the source of the issue yet..

**Comment by 75lb** [comment]
pleased to hear it helps 👍
