### ISSUE TITLE
Inline @link tags are not being transformed by link.hbs

### ISSUE THREAD

**Issue by ericSpence** [jsdoc2md/grunt-jsdoc-to-markdown#12]
I have a custom link.hbs partial that transforms all other links to the necessary format. However inline jsdoc @link do not seem to be transformed leaving behind broken links. Are these transformed by a different partial or does grunt-jsdoc-to-markdown not support the @link jsdoc tag?

**Comment by 75lb** [comment]
jsdoc2md does support the `@link` tag, [this helper](https://github.com/jsdoc2md/dmd/blob/master/helpers/ddata.js#L206) resolves the link to a target.. You will need to supply a valid namepath to the `@link` tag, run `jsdoc2md --namepaths your-code.js` to see a list of all valid namepaths.
