### ISSUE TITLE
Fatal error: Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by hyanwong** [jsdoc2md/grunt-jsdoc-to-markdown#14]
I'm getting `Fatal error: Cannot read property 'pipe' of undefined` when running the following gruntfile config ("grunt-jsdoc-to-markdown": "^5.0.0"). I'm not sure how to debug this to give more info. Have you any suggestions for how to triage this?

```
    jsdoc2md: {
      separateOutputFilePerInput: {
        files: [
          { expand: true,
            cwd: '<%=pkg.directories.js_src%>',
            src: '**/*.js', 
            dest: 'docs/src',
            ext: '.md' }
        ]
      },
      withOptions: {
        options: {
          'heading-depth': 4,
          'global-index-format': 'none'
        }
      }
    },
    ...
```

**Comment by 75lb** [comment]
Hi, I can't reproduce this... could you please provide a functional test case I can run and see failing.. I'll need input source code and a full gruntfile.

**Comment by hyanwong** [comment]
Weirdly this has started working for me again now. I have no idea why, but will close this and reopen if I can reproduce
