### ISSUE TITLE
Warning: Must set either .files or .source Use --force to continue.

### ISSUE THREAD

**Issue by gordonwoodhull** [jsdoc2md/grunt-jsdoc-to-markdown#15]
My Gruntfile has worked for many years with 

```js
        jsdoc2md: {
            dist: {
                src: '<%= conf.dist %>/<%= conf.pkg.name %>.js',
                dest: 'docs/api-latest.md'
            }
        },
```
https://github.com/dc-js/dc.js/blob/34474b23e95bda2043985c47b83525ac2b851258/Gruntfile.js#L196-L201

But it started complaining with the warning in the title for the past version or two.

I have tried changing `src` to `source` and `files`, to no avail.

Any ideas?

**Comment by 75lb** [comment]
That's odd, i've tried but failed to reproduce this issue.. 

Insert `console.log(options)` directly above [this line](https://github.com/jsdoc2md/grunt-jsdoc-to-markdown/blob/master/tasks/jsdoc2md.js#L15), are the correct filenames and options being passed into jsdoc2md? 

The options object should look something like this: 

```js
{
  'no-gfm': true,
  'no-cache': true,
  files: [ 'test/fixture/object.js' ]
}
```

**Comment by gordonwoodhull** [comment]
This is a strange intermittent bug. When I added the log, it started working! 

From that point on, after reinstalling `grunt-jsdoc-to-markdown` and all of `node_modules`, everything is ok. So I'll close this.

I didn't realize how small this module is, will definitely help troubleshoot if I see this again.

**Comment by gordonwoodhull** [comment]
FWIW, in any case anyone runs into the above error, the root cause for me is running rollup using grunt-shell rather than grunt-rollup. It seems that the shell task is not completely finished, so the source .js temporarily does not exist.

Dug into it, didn't understand it, I just avoid running those commands in sequence as a workaround for now.
