### ISSUE TITLE
add support for grunt 1.0.0

### ISSUE THREAD

**Issue by sagiegurari** [jsdoc2md/grunt-jsdoc-to-markdown#6]
since the peer dependency is of ~0.4.5, new grunt version (1.x.x) is not supported.
Can you please update the needed?

**Comment by 75lb** [comment]
yes, will do at some point in the next few days

**Comment by sagiegurari** [comment]
Thanks

**Comment by 75lb** [comment]
fixed and release in v1.2.1 - please let me know if there are any other issues

**Comment by sagiegurari** [comment]
thanks :+1:

**Comment by sagiegurari** [comment]
works great, thanks
